// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AccessSource } from "./AccessSource";
import type { AccessType } from "./AccessType";

export type AccessDocument = { type: AccessType, file_id: string, source: AccessSource, last_access: string, access_count: number, };
