// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AnnotationSource } from "./AnnotationSource";
import type { AnnotationType } from "./AnnotationType";
import type { JsonValue } from "./serde_json/JsonValue";

export type AnnotationDocument = { type: AnnotationType, file_id: string, source: AnnotationSource, plugin_name: string, data: JsonValue, status: string, error: string | null, annotated_at: string, updated_at: string, };
