// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CredentialPermissions } from "./CredentialPermissions";
import type { CredentialType } from "./CredentialType";

export type CredentialDocument = { type: CredentialType, access_key_id: string, secret_key_hash: string, name: string, enabled: boolean, created_at: string, last_seen: string | null, permissions: CredentialPermissions, };
