// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FilesystemType } from "./FilesystemType";
import type { NodeAvailability } from "./NodeAvailability";

export type FilesystemDocument = { type: FilesystemType, filesystem_id: string, friendly_name: string, owning_node_id: string, export_root: string, availability: Array<NodeAvailability>, created_at: string, };
