// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LabelAssignmentType } from "./LabelAssignmentType";

export type LabelAssignmentDocument = { type: LabelAssignmentType, file_id: string, labels: Array<string>, updated_at: string, updated_by: string, };
