// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LabelRuleType } from "./LabelRuleType";

export type LabelRuleDocument = { type: LabelRuleType, node_id: string, path_prefix: string, labels: Array<string>, name: string, enabled: boolean, created_at: string, };
