// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type MigratedFrom = { node_id: string, export_path: string, migrated_at: string, };
