// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type MountSource = { node_id: string, export_path: string, } | { federated_import_id: string, } | { label: string, };
