// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type NetworkMount = { 
/**
 * See docs/architecture/07-vfs-access.md for the lazy-resolution invariant.
 */
mount_id: string, filesystem_id: string, remote_node_id: string, remote_base_export_path: string, local_mount_path: string, mount_type: string, priority: number, };
