// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type NetworkMount = { mount_id: string, filesystem_id: string, remote_node_id: string, remote_base_export_path: string, local_mount_path: string, mount_type: string, priority: number, };
