// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { NetworkMount } from "./NetworkMount";
import type { NodeStatus } from "./NodeStatus";
import type { NodeType } from "./NodeType";
import type { StorageEntry } from "./StorageEntry";

export type NodeDocument = { type: NodeType, friendly_name: string, platform: string, status: NodeStatus, last_heartbeat: string, vfs_capable: boolean, vfs_backend: string | null, capabilities: Array<string>, storage: Array<StorageEntry> | null, network_mounts: Array<NetworkMount> | null, };
