// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type NodeAvailability = { node_id: string, local_mount_path: string, 
/**
 * "local" when this is the owning node, otherwise the OS mount type
 * (e.g. "nfs", "cifs", "icloud_local", "gdrive_local").
 */
mount_type: string, last_seen: string, };
