// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ReplicaSource } from "./ReplicaSource";
import type { ReplicaType } from "./ReplicaType";

export type ReplicaDocument = { type: ReplicaType, file_id: string, target_name: string, source: ReplicaSource, backend: string, remote_key: string, replicated_at: string, source_mtime: string, source_size: number, checksum: string | null, status: string, };
