// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ReplicationRuleSource } from "./ReplicationRuleSource";
import type { ReplicationRuleType } from "./ReplicationRuleType";
import type { Step } from "./Step";
import type { StepResult } from "./StepResult";

export type ReplicationRuleDocument = { type: ReplicationRuleType, name: string, target_name: string, source: ReplicationRuleSource, steps: Array<Step>, default_result: StepResult, enabled: boolean, created_at: string, updated_at: string, };
