// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { StepResult } from "./StepResult";

export type Step = { op: string, invert: boolean, on_match: StepResult | null, };
