// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CloudSnapshot } from "./CloudSnapshot";
import type { FilesystemSnapshot } from "./FilesystemSnapshot";
import type { UtilizationType } from "./UtilizationType";

export type UtilizationSnapshotDocument = { type: UtilizationType, node_id: string, captured_at: string, filesystems: Array<FilesystemSnapshot> | null, cloud: CloudSnapshot | null, };
