// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MountEntry } from "./MountEntry";
import type { VirtualDirectoryType } from "./VirtualDirectoryType";

export type VirtualDirectoryDocument = { type: VirtualDirectoryType, inode: number, virtual_path: string, name: string, parent_path: string | null, system: boolean | null, created_at: string, enforce_steps_on_children: boolean, mounts: Array<MountEntry>, };
